packages:
  - examples/*
  - packages/*
  - .
ignoredBuiltDependencies:
  - bufferutil
  - keccak
  - simple-git-hooks
  - utf-8-validate
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
overrides:
  '@kheopskit/core': link:packages/core
  '@kheopskit/react': link:packages/react
