packages:
  - examples/*
  - packages/*
  - .
allowBuilds:
  "@biomejs/biome": true
  "@reown/appkit": false
  "@tailwindcss/oxide": true
  bufferutil: false
  esbuild: true
  keccak: false
  sharp: false
  simple-git-hooks: true
  utf-8-validate: false
overrides:
  "@kheopskit/core": link:packages/core
  "@kheopskit/react": link:packages/react
  "axios@>=1.0.0 <1.15.2": ^1.15.2
  "postcss@<8.5.10": ^8.5.10
  "hono@<4.12.18": ^4.12.18
  "ws@>=8.0.0 <8.20.1": ^8.20.1

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - hono
