packages:
  - examples/*
  - packages/*
  - . # for changesets to sync root version
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
overrides:
  '@kheopskit/core': link:packages/core
  '@kheopskit/react': link:packages/react
